spring:
  application:
    name: Payment
    
server:
  port: 8086
  
composition:
  messagebroker:
    type: rabbitmq
    host: localhost
    port: 5672
    exchange: composition
  fragmentmanager:
    url: http://localhost:8083
    
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:2222/eureka